// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/chaincode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chaincode_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_chaincode_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{0}
}

// Empty message for parameterless requests
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_chaincode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{0}
}

// State management messages
type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{2}
}

func (x *GetStateResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStateRequest) Reset() {
	*x = PutStateRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStateRequest) ProtoMessage() {}

func (x *PutStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStateRequest.ProtoReflect.Descriptor instead.
func (*PutStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{3}
}

func (x *PutStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutStateRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStateResponse) Reset() {
	*x = PutStateResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStateResponse) ProtoMessage() {}

func (x *PutStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStateResponse.ProtoReflect.Descriptor instead.
func (*PutStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{4}
}

func (x *PutStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateRequest) Reset() {
	*x = DeleteStateRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateRequest) ProtoMessage() {}

func (x *DeleteStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateResponse) Reset() {
	*x = DeleteStateResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateResponse) ProtoMessage() {}

func (x *DeleteStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateResponse.ProtoReflect.Descriptor instead.
func (*DeleteStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Range query messages
type GetStateByRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        string                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateByRangeRequest) Reset() {
	*x = GetStateByRangeRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateByRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateByRangeRequest) ProtoMessage() {}

func (x *GetStateByRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateByRangeRequest.ProtoReflect.Descriptor instead.
func (*GetStateByRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateByRangeRequest) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *GetStateByRangeRequest) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

type GetStateByRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*KeyValue            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Bookmark      string                 `protobuf:"bytes,3,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateByRangeResponse) Reset() {
	*x = GetStateByRangeResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateByRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateByRangeResponse) ProtoMessage() {}

func (x *GetStateByRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateByRangeResponse.ProtoReflect.Descriptor instead.
func (*GetStateByRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{8}
}

func (x *GetStateByRangeResponse) GetResults() []*KeyValue {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetStateByRangeResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetStateByRangeResponse) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

type GetStateByPartialCompositeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateByPartialCompositeKeyRequest) Reset() {
	*x = GetStateByPartialCompositeKeyRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateByPartialCompositeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateByPartialCompositeKeyRequest) ProtoMessage() {}

func (x *GetStateByPartialCompositeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateByPartialCompositeKeyRequest.ProtoReflect.Descriptor instead.
func (*GetStateByPartialCompositeKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{9}
}

func (x *GetStateByPartialCompositeKeyRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetStateByPartialCompositeKeyRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetStateByPartialCompositeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*KeyValue            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Bookmark      string                 `protobuf:"bytes,3,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateByPartialCompositeKeyResponse) Reset() {
	*x = GetStateByPartialCompositeKeyResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateByPartialCompositeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateByPartialCompositeKeyResponse) ProtoMessage() {}

func (x *GetStateByPartialCompositeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateByPartialCompositeKeyResponse.ProtoReflect.Descriptor instead.
func (*GetStateByPartialCompositeKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{10}
}

func (x *GetStateByPartialCompositeKeyResponse) GetResults() []*KeyValue {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetStateByPartialCompositeKeyResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetStateByPartialCompositeKeyResponse) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_chaincode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{11}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Transaction context messages
type GetTransactionIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionIDResponse) Reset() {
	*x = GetTransactionIDResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionIDResponse) ProtoMessage() {}

func (x *GetTransactionIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionIDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionIDResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetChannelIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelIDResponse) Reset() {
	*x = GetChannelIDResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelIDResponse) ProtoMessage() {}

func (x *GetChannelIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelIDResponse.ProtoReflect.Descriptor instead.
func (*GetChannelIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{13}
}

func (x *GetChannelIDResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       []byte                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatorResponse) Reset() {
	*x = GetCreatorResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatorResponse) ProtoMessage() {}

func (x *GetCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatorResponse.ProtoReflect.Descriptor instead.
func (*GetCreatorResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{14}
}

func (x *GetCreatorResponse) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

type GetTransactionTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionTimestampResponse) Reset() {
	*x = GetTransactionTimestampResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionTimestampResponse) ProtoMessage() {}

func (x *GetTransactionTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionTimestampResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionTimestampResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransactionTimestampResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Event messages
type SetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEventRequest) Reset() {
	*x = SetEventRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEventRequest) ProtoMessage() {}

func (x *SetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEventRequest.ProtoReflect.Descriptor instead.
func (*SetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{16}
}

func (x *SetEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEventResponse) Reset() {
	*x = SetEventResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEventResponse) ProtoMessage() {}

func (x *SetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEventResponse.ProtoReflect.Descriptor instead.
func (*SetEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{17}
}

func (x *SetEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Chaincode invocation messages
type InvokeChaincodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeName string                 `protobuf:"bytes,1,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	Function      string                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeChaincodeRequest) Reset() {
	*x = InvokeChaincodeRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeChaincodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeChaincodeRequest) ProtoMessage() {}

func (x *InvokeChaincodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeChaincodeRequest.ProtoReflect.Descriptor instead.
func (*InvokeChaincodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{18}
}

func (x *InvokeChaincodeRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *InvokeChaincodeRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *InvokeChaincodeRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InvokeChaincodeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type InvokeChaincodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeChaincodeResponse) Reset() {
	*x = InvokeChaincodeResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeChaincodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeChaincodeResponse) ProtoMessage() {}

func (x *InvokeChaincodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeChaincodeResponse.ProtoReflect.Descriptor instead.
func (*InvokeChaincodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{19}
}

func (x *InvokeChaincodeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeChaincodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeChaincodeResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Logging messages
type LogMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=chaincode.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessageRequest) Reset() {
	*x = LogMessageRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessageRequest) ProtoMessage() {}

func (x *LogMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessageRequest.ProtoReflect.Descriptor instead.
func (*LogMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{20}
}

func (x *LogMessageRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessageResponse) Reset() {
	*x = LogMessageResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessageResponse) ProtoMessage() {}

func (x *LogMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessageResponse.ProtoReflect.Descriptor instead.
func (*LogMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{21}
}

func (x *LogMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Chaincode execution request/response (for the Rust side)
type ChaincodeExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaincodeId   string                 `protobuf:"bytes,1,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	Function      string                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Creator       []byte                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeExecutionRequest) Reset() {
	*x = ChaincodeExecutionRequest{}
	mi := &file_proto_chaincode_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeExecutionRequest) ProtoMessage() {}

func (x *ChaincodeExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeExecutionRequest.ProtoReflect.Descriptor instead.
func (*ChaincodeExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{22}
}

func (x *ChaincodeExecutionRequest) GetChaincodeId() string {
	if x != nil {
		return x.ChaincodeId
	}
	return ""
}

func (x *ChaincodeExecutionRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ChaincodeExecutionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ChaincodeExecutionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ChaincodeExecutionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChaincodeExecutionRequest) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *ChaincodeExecutionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChaincodeExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Events        []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	StateChanges  []*StateChange         `protobuf:"bytes,5,rep,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaincodeExecutionResponse) Reset() {
	*x = ChaincodeExecutionResponse{}
	mi := &file_proto_chaincode_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeExecutionResponse) ProtoMessage() {}

func (x *ChaincodeExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeExecutionResponse.ProtoReflect.Descriptor instead.
func (*ChaincodeExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{23}
}

func (x *ChaincodeExecutionResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChaincodeExecutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChaincodeExecutionResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChaincodeExecutionResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ChaincodeExecutionResponse) GetStateChanges() []*StateChange {
	if x != nil {
		return x.StateChanges
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_chaincode_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{24}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // PUT, DELETE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	mi := &file_proto_chaincode_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaincode_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_proto_chaincode_proto_rawDescGZIP(), []int{25}
}

func (x *StateChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateChange) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

var File_proto_chaincode_proto protoreflect.FileDescriptor

const file_proto_chaincode_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chaincode.proto\x12\tchaincode\"\a\n" +
	"\x05Empty\"#\n" +
	"\x0fGetStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\x10GetStateResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"9\n" +
	"\x0fPutStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"B\n" +
	"\x10PutStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x12DeleteStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"E\n" +
	"\x13DeleteStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\x16GetStateByRangeRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\tR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\tR\x06endKey\"\x7f\n" +
	"\x17GetStateByRangeResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.chaincode.KeyValueR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1a\n" +
	"\bbookmark\x18\x03 \x01(\tR\bbookmark\"[\n" +
	"$GetStateByPartialCompositeKeyRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\x8d\x01\n" +
	"%GetStateByPartialCompositeKeyResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.chaincode.KeyValueR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1a\n" +
	"\bbookmark\x18\x03 \x01(\tR\bbookmark\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"A\n" +
	"\x18GetTransactionIDResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"5\n" +
	"\x14GetChannelIDResponse\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\".\n" +
	"\x12GetCreatorResponse\x12\x18\n" +
	"\acreator\x18\x01 \x01(\fR\acreator\"?\n" +
	"\x1fGetTransactionTimestampResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"?\n" +
	"\x0fSetEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"B\n" +
	"\x10SetEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x89\x01\n" +
	"\x16InvokeChaincodeRequest\x12%\n" +
	"\x0echaincode_name\x18\x01 \x01(\tR\rchaincodeName\x12\x1a\n" +
	"\bfunction\x18\x02 \x01(\tR\bfunction\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"e\n" +
	"\x17InvokeChaincodeResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"X\n" +
	"\x11LogMessageRequest\x12)\n" +
	"\x05level\x18\x01 \x01(\x0e2\x13.chaincode.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x12LogMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xec\x01\n" +
	"\x19ChaincodeExecutionRequest\x12!\n" +
	"\fchaincode_id\x18\x01 \x01(\tR\vchaincodeId\x12\x1a\n" +
	"\bfunction\x18\x02 \x01(\tR\bfunction\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\x12\x18\n" +
	"\acreator\x18\x06 \x01(\fR\acreator\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xcf\x01\n" +
	"\x1aChaincodeExecutionResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12(\n" +
	"\x06events\x18\x04 \x03(\v2\x10.chaincode.EventR\x06events\x12;\n" +
	"\rstate_changes\x18\x05 \x03(\v2\x16.chaincode.StateChangeR\fstateChanges\"5\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"S\n" +
	"\vStateChange\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation*4\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xd6\a\n" +
	"\rChaincodeShim\x12C\n" +
	"\bGetState\x12\x1a.chaincode.GetStateRequest\x1a\x1b.chaincode.GetStateResponse\x12C\n" +
	"\bPutState\x12\x1a.chaincode.PutStateRequest\x1a\x1b.chaincode.PutStateResponse\x12L\n" +
	"\vDeleteState\x12\x1d.chaincode.DeleteStateRequest\x1a\x1e.chaincode.DeleteStateResponse\x12X\n" +
	"\x0fGetStateByRange\x12!.chaincode.GetStateByRangeRequest\x1a\".chaincode.GetStateByRangeResponse\x12\x82\x01\n" +
	"\x1dGetStateByPartialCompositeKey\x12/.chaincode.GetStateByPartialCompositeKeyRequest\x1a0.chaincode.GetStateByPartialCompositeKeyResponse\x12I\n" +
	"\x10GetTransactionID\x12\x10.chaincode.Empty\x1a#.chaincode.GetTransactionIDResponse\x12A\n" +
	"\fGetChannelID\x12\x10.chaincode.Empty\x1a\x1f.chaincode.GetChannelIDResponse\x12=\n" +
	"\n" +
	"GetCreator\x12\x10.chaincode.Empty\x1a\x1d.chaincode.GetCreatorResponse\x12W\n" +
	"\x17GetTransactionTimestamp\x12\x10.chaincode.Empty\x1a*.chaincode.GetTransactionTimestampResponse\x12C\n" +
	"\bSetEvent\x12\x1a.chaincode.SetEventRequest\x1a\x1b.chaincode.SetEventResponse\x12X\n" +
	"\x0fInvokeChaincode\x12!.chaincode.InvokeChaincodeRequest\x1a\".chaincode.InvokeChaincodeResponse\x12I\n" +
	"\n" +
	"LogMessage\x12\x1c.chaincode.LogMessageRequest\x1a\x1d.chaincode.LogMessageResponseB+Z)github.com/beacon-blockchain/sdk-go/protob\x06proto3"

var (
	file_proto_chaincode_proto_rawDescOnce sync.Once
	file_proto_chaincode_proto_rawDescData []byte
)

func file_proto_chaincode_proto_rawDescGZIP() []byte {
	file_proto_chaincode_proto_rawDescOnce.Do(func() {
		file_proto_chaincode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chaincode_proto_rawDesc), len(file_proto_chaincode_proto_rawDesc)))
	})
	return file_proto_chaincode_proto_rawDescData
}

var file_proto_chaincode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chaincode_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_chaincode_proto_goTypes = []any{
	(LogLevel)(0),                                 // 0: chaincode.LogLevel
	(*Empty)(nil),                                 // 1: chaincode.Empty
	(*GetStateRequest)(nil),                       // 2: chaincode.GetStateRequest
	(*GetStateResponse)(nil),                      // 3: chaincode.GetStateResponse
	(*PutStateRequest)(nil),                       // 4: chaincode.PutStateRequest
	(*PutStateResponse)(nil),                      // 5: chaincode.PutStateResponse
	(*DeleteStateRequest)(nil),                    // 6: chaincode.DeleteStateRequest
	(*DeleteStateResponse)(nil),                   // 7: chaincode.DeleteStateResponse
	(*GetStateByRangeRequest)(nil),                // 8: chaincode.GetStateByRangeRequest
	(*GetStateByRangeResponse)(nil),               // 9: chaincode.GetStateByRangeResponse
	(*GetStateByPartialCompositeKeyRequest)(nil),  // 10: chaincode.GetStateByPartialCompositeKeyRequest
	(*GetStateByPartialCompositeKeyResponse)(nil), // 11: chaincode.GetStateByPartialCompositeKeyResponse
	(*KeyValue)(nil),                              // 12: chaincode.KeyValue
	(*GetTransactionIDResponse)(nil),              // 13: chaincode.GetTransactionIDResponse
	(*GetChannelIDResponse)(nil),                  // 14: chaincode.GetChannelIDResponse
	(*GetCreatorResponse)(nil),                    // 15: chaincode.GetCreatorResponse
	(*GetTransactionTimestampResponse)(nil),       // 16: chaincode.GetTransactionTimestampResponse
	(*SetEventRequest)(nil),                       // 17: chaincode.SetEventRequest
	(*SetEventResponse)(nil),                      // 18: chaincode.SetEventResponse
	(*InvokeChaincodeRequest)(nil),                // 19: chaincode.InvokeChaincodeRequest
	(*InvokeChaincodeResponse)(nil),               // 20: chaincode.InvokeChaincodeResponse
	(*LogMessageRequest)(nil),                     // 21: chaincode.LogMessageRequest
	(*LogMessageResponse)(nil),                    // 22: chaincode.LogMessageResponse
	(*ChaincodeExecutionRequest)(nil),             // 23: chaincode.ChaincodeExecutionRequest
	(*ChaincodeExecutionResponse)(nil),            // 24: chaincode.ChaincodeExecutionResponse
	(*Event)(nil),                                 // 25: chaincode.Event
	(*StateChange)(nil),                           // 26: chaincode.StateChange
}
var file_proto_chaincode_proto_depIdxs = []int32{
	12, // 0: chaincode.GetStateByRangeResponse.results:type_name -> chaincode.KeyValue
	12, // 1: chaincode.GetStateByPartialCompositeKeyResponse.results:type_name -> chaincode.KeyValue
	0,  // 2: chaincode.LogMessageRequest.level:type_name -> chaincode.LogLevel
	25, // 3: chaincode.ChaincodeExecutionResponse.events:type_name -> chaincode.Event
	26, // 4: chaincode.ChaincodeExecutionResponse.state_changes:type_name -> chaincode.StateChange
	2,  // 5: chaincode.ChaincodeShim.GetState:input_type -> chaincode.GetStateRequest
	4,  // 6: chaincode.ChaincodeShim.PutState:input_type -> chaincode.PutStateRequest
	6,  // 7: chaincode.ChaincodeShim.DeleteState:input_type -> chaincode.DeleteStateRequest
	8,  // 8: chaincode.ChaincodeShim.GetStateByRange:input_type -> chaincode.GetStateByRangeRequest
	10, // 9: chaincode.ChaincodeShim.GetStateByPartialCompositeKey:input_type -> chaincode.GetStateByPartialCompositeKeyRequest
	1,  // 10: chaincode.ChaincodeShim.GetTransactionID:input_type -> chaincode.Empty
	1,  // 11: chaincode.ChaincodeShim.GetChannelID:input_type -> chaincode.Empty
	1,  // 12: chaincode.ChaincodeShim.GetCreator:input_type -> chaincode.Empty
	1,  // 13: chaincode.ChaincodeShim.GetTransactionTimestamp:input_type -> chaincode.Empty
	17, // 14: chaincode.ChaincodeShim.SetEvent:input_type -> chaincode.SetEventRequest
	19, // 15: chaincode.ChaincodeShim.InvokeChaincode:input_type -> chaincode.InvokeChaincodeRequest
	21, // 16: chaincode.ChaincodeShim.LogMessage:input_type -> chaincode.LogMessageRequest
	3,  // 17: chaincode.ChaincodeShim.GetState:output_type -> chaincode.GetStateResponse
	5,  // 18: chaincode.ChaincodeShim.PutState:output_type -> chaincode.PutStateResponse
	7,  // 19: chaincode.ChaincodeShim.DeleteState:output_type -> chaincode.DeleteStateResponse
	9,  // 20: chaincode.ChaincodeShim.GetStateByRange:output_type -> chaincode.GetStateByRangeResponse
	11, // 21: chaincode.ChaincodeShim.GetStateByPartialCompositeKey:output_type -> chaincode.GetStateByPartialCompositeKeyResponse
	13, // 22: chaincode.ChaincodeShim.GetTransactionID:output_type -> chaincode.GetTransactionIDResponse
	14, // 23: chaincode.ChaincodeShim.GetChannelID:output_type -> chaincode.GetChannelIDResponse
	15, // 24: chaincode.ChaincodeShim.GetCreator:output_type -> chaincode.GetCreatorResponse
	16, // 25: chaincode.ChaincodeShim.GetTransactionTimestamp:output_type -> chaincode.GetTransactionTimestampResponse
	18, // 26: chaincode.ChaincodeShim.SetEvent:output_type -> chaincode.SetEventResponse
	20, // 27: chaincode.ChaincodeShim.InvokeChaincode:output_type -> chaincode.InvokeChaincodeResponse
	22, // 28: chaincode.ChaincodeShim.LogMessage:output_type -> chaincode.LogMessageResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_chaincode_proto_init() }
func file_proto_chaincode_proto_init() {
	if File_proto_chaincode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chaincode_proto_rawDesc), len(file_proto_chaincode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chaincode_proto_goTypes,
		DependencyIndexes: file_proto_chaincode_proto_depIdxs,
		EnumInfos:         file_proto_chaincode_proto_enumTypes,
		MessageInfos:      file_proto_chaincode_proto_msgTypes,
	}.Build()
	File_proto_chaincode_proto = out.File
	file_proto_chaincode_proto_goTypes = nil
	file_proto_chaincode_proto_depIdxs = nil
}
