[package]
name = "beacon-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
beacon-core = { path = "../beacon-core" }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
